title: Gail Terman Portfolio
description: UX Portfolio
baseurl: "/ux-portfolio" # the subpath of your site, e.g. /blog
url: "https://gailbear.github.io" # the base hostname & protocol for your site, e.g. http://example.com

theme: just-the-docs
permalink: pretty

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
#aux_links:
#  "Just the Docs on GitHub":
#    - "https://github.com/pmarsceill/just-the-docs"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2020 Gail Terman"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: #UA-2709176-10

plugins:
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
